"""Vendor OUI (Organizationally Unique Identifier) registry.

Loads vendor-to-OUI mappings from a JSON database generated by
``scripts/update_vendor_db.py`` (source: Wireshark manuf file).
"""

from __future__ import annotations

import json
from functools import cache
from importlib import resources

from macspoofer.utils.exceptions import CustomException, ErrorCode


@cache
def _vendor_db() -> dict[str, list[str]]:
    """Load the bundled vendor database, caching it after the first call.

    Loaded on demand rather than at import time so that a missing or corrupt
    database is reported as a normal error by the CLI, and so ``--help`` and
    ``--version`` do not pay for parsing it.

    Raises:
        CustomException: If the database cannot be read or parsed
    """
    try:
        pkg = resources.files("macspoofer").joinpath("data/vendors.json")
        with pkg.open(encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError) as err:
        raise CustomException(
            message=f"Failed to load the bundled vendor database: {err}",
            error_code=ErrorCode.VENDOR_DB_LOAD_FAILED,
        ) from err


class VendorRegistry:
    """Registry of vendor OUI prefixes for MAC address generation."""

    FEATURED: list[str] = [
        "Samsung",
        "Apple",
        "Intel",
        "Microsoft",
        "Huawei",
        "Google",
        "Cisco",
        "Dell",
        "HP",
        "Amazon",
        "Xiaomi",
        "Nokia",
        "Sony",
        "LG",
        "Motorola",
        "TP-Link",
        "OPPO",
        "Vivo",
        "ZTE",
        "Espressif",
    ]

    NAMES: list[str] = ["Total Random", *FEATURED]

    @classmethod
    def get_ouis_for_vendor(cls, vendor_name: str) -> list[str] | None:
        """Get OUI list for a specific vendor.

        Args:
            vendor_name: Name of the vendor (case-sensitive, must match JSON key)

        Returns:
            List of OUI strings, or None if vendor not found
        """
        return _vendor_db().get(vendor_name)

    @classmethod
    def get_oui_map(cls) -> dict[str, list[str]]:
        """Get the full vendor-to-OUI mapping."""
        return _vendor_db()

    @classmethod
    def search(cls, query: str, limit: int = 25) -> list[str]:
        """Search vendor names by substring (case-insensitive).

        Args:
            query: Search string
            limit: Maximum number of results to return

        Returns:
            List of matching vendor names, sorted by OUI count (descending)
        """
        db = _vendor_db()
        q = query.lower()
        matches = [name for name in db if q in name.lower()]
        matches.sort(key=lambda n: len(db[n]), reverse=True)
        return matches[:limit]

    @classmethod
    def vendor_count(cls) -> int:
        """Return total number of vendors in the database."""
        return len(_vendor_db())
