"""Vendor OUI (Organizationally Unique Identifier) registry.

Loads vendor-to-OUI mappings from a JSON database generated by
``scripts/build_vendor_db.py`` (source: Wireshark manuf file).
"""

from __future__ import annotations

import json
import os

_DATA_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "vendors.json"
)


def _load_vendor_db() -> dict[str, list[str]]:
    with open(_DATA_PATH, encoding="utf-8") as f:
        return json.load(f)


_VENDOR_DB: dict[str, list[str]] = _load_vendor_db()


class VendorRegistry:
    """Registry of vendor OUI prefixes for MAC address generation."""

    FEATURED: list[str] = [
        "Samsung",
        "Apple",
        "Intel",
        "Microsoft",
        "Huawei",
        "Google",
        "Cisco",
        "Dell",
        "HP",
        "Amazon",
        "Xiaomi",
        "Nokia",
        "Sony",
        "LG",
        "Motorola",
        "TP-Link",
        "OPPO",
        "Vivo",
        "ZTE",
        "Espressif",
    ]

    NAMES: list[str] = ["Total Random", *FEATURED]

    @classmethod
    def get_ouis_for_vendor(cls, vendor_name: str) -> list[str] | None:
        """Get OUI list for a specific vendor.

        Args:
            vendor_name: Name of the vendor (case-sensitive, must match JSON key)

        Returns:
            List of OUI strings, or None if vendor not found
        """
        return _VENDOR_DB.get(vendor_name)

    @classmethod
    def get_oui_map(cls) -> dict[str, list[str]]:
        """Get the full vendor-to-OUI mapping."""
        return _VENDOR_DB

    @classmethod
    def search(cls, query: str, limit: int = 25) -> list[str]:
        """Search vendor names by substring (case-insensitive).

        Args:
            query: Search string
            limit: Maximum number of results to return

        Returns:
            List of matching vendor names, sorted by OUI count (descending)
        """
        q = query.lower()
        matches = [name for name in _VENDOR_DB if q in name.lower()]
        matches.sort(key=lambda n: len(_VENDOR_DB[n]), reverse=True)
        return matches[:limit]

    @classmethod
    def vendor_count(cls) -> int:
        """Return total number of vendors in the database."""
        return len(_VENDOR_DB)
