name: MacSpoofer CI

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y iproute2 net-tools python3-rich

      - name: Create dummy interface (wlan0)
        run: |
          sudo ip link add wlan0 type dummy
          sudo ip link set wlan0 up
          echo "Created dummy interface:"
          ip link show wlan0

      - name: Run MacSpoofer
        run: |
          echo "Running MacSpoofer on dummy wlan0..."
          sudo python3 ./src/spoofer.py wlan0
          echo "After spoofing:"
          ip link show wlan0 | grep ether

      - name: Verify MAC change
        run: |
          NEW_MAC=$(ip link show wlan0 | awk '/ether/ {print $2}')
          echo "Spoofed MAC: $NEW_MAC"
          if [[ "$NEW_MAC" == "02:00:00:00:00:00" ]]; then
            echo "MAC was not changed!"
            exit 1
          else
            echo "MAC spoof successful"
          fi
